apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fyxt-app.fullname" . }}
  labels:
    {{- include "fyxt-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-secret: {{ .Values.secret.appSecret | quote }}
